AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'db/schema.rb'

Documentation:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - Rakefile

Metrics/LineLength:
  Max: 120

Style/RescueModifier:
  Enabled: false
