AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Documentation:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - Rakefile

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RescueModifier:
  Enabled: false
