sudo: false
language: ruby
cache:
  bundler: true
  directories:
  - .downloads
  - node_modules
  - tmp/cache/assets/test
  - vendor/assets/bower_components
env:
  global:
  - secure: OHty0sCWbCAsxw8vLWmQLe2uBu8aR7zwKXh4aO8XipkNqIQSyVF3Q/iNC2DOclOmomT/C2wp2XWLysazJ5oyYpkooTe0wh9Bl2I3J6JqF7aynLzmk8eT0BoP/MZwX0lbCI11Z2JVW349xipku/vBVoucN40P6j5FfgZjTJYm5JE=
  - secure: SVw7sxOncYt1Tp9QoPLmKSw2IxpF1u3UyfmxIG3hqjkCVrNjYTehBfnS/pxoGVugrq8q9PQ9uJPZlmOp5IKIlJhyZ6kdpq2LjRxjgAPC935qOEgsu4OM1olE0G1oqdyDBv/tePmJFmr0ViUfCIIv464g+cYd81kFzcwaeXgKjOM=
  - DATABASE_URL=postgres://postgres@localhost:5432/travis_ci_test
  - PATH=$PWD/bin:$PATH
node_js:
- '0.10'
before_script:
- '[ -d .downloads ] || mkdir .downloads'
- (cd .downloads; [ -d prince-9.0r5-linux-amd64-static ] || curl -s http://www.princexml.com/download/prince-9.0r5-linux-amd64-static.tar.gz | tar xzf -)
- echo $PWD | ./.downloads/prince-9.0r5-linux-amd64-static/install.sh
- npm install
- ./bin/rake db:setup RAILS_ENV=test
after_script:
- "./node_modules/.bin/travis-notify-geckoboard -a $GECKOBOARD_API_KEY -w $GECKOBOARD_WIDGET_KEY"
deploy:
  provider: heroku
  api_key:
    secure: St3obQR6V1Ym4bB8VX0kZncM3twf9JymThAi7rIOLFn6Ipp1Z/WuLZBwClVWt1jShJ38ZZtTvr6dGflABpFteh00Z1atLq4R5T3+k1MG9oeL21ejsM+4BbU7zMNcQsaHNkj/YFhCtOhG/ZZkRq+0QgACFO9zMNMkbAL1bGg/Lf8=
  app: ggp-record-of-guidance
  on:
    repo: guidance-guarantee-programme/record_of_guidance
  run: "./bin/rake db:migrate"
