sudo: false
language: ruby
addons:
  chrome: stable
services:
- redis-server
- postgresql
cache:
  bundler: true
  directories:
  - '.downloads'
  - node_modules
  - tmp/cache/assets/test
  - vendor/assets/bower_components
env:
  global:
  - secure: ZbggxPXsIVr8W4yO7oLH0Ps+jaCcZcwvR3/wUCjwtaO/FdmHhE8LkN9If14IYyiegEmF4kmlqH03+Svb1CGOgt54kQ4wCuN8dCNH+hGS39Vn/E2ngC/h5U/wf99m4IVzBPzg0IcKN9OWCWzRRMUM+X0Zq04zuekWwUMKlERAajk=
  - secure: TalQfqJYJofCCUZdzC75EEQtNtD7DyFDFa0IGziaz0H8xxGF7sTG/Sn02ufVxXEylfdCYFQYERfjBz/aajSUZ/7mVDFvokiJaYbGCZNboKmwzfRcYxNz5k4MwrTzPdkebjyEYaYHsMrdOmNkI+4UKiwqkew4n10EC++vfDgyTYQ=
  - DATABASE_URL=postgres://postgres@localhost:5432/travis_ci_test
node_js:
- '0.10'
before_script:
- '[ -d .downloads ] || mkdir .downloads'
- '(cd .downloads; [ -d prince-9.0r5-linux-amd64-static ] || curl -s https://www.princexml.com/download/prince-9.0r5-linux-amd64-static.tar.gz | tar xzf -)'
- echo $PWD | ./.downloads/prince-9.0r5-linux-amd64-static/install.sh
- npm install
- './bin/rake db:setup RAILS_ENV=test'
notifications:
  slack:
    secure: YSz3iC+QIFKS108cIAc+bmImetKRRb0fij9g7skft+Ug9Err4JDMGo0fX+2vHL9XOk+tx5wWJZjy/HSpHd5kMAw8+ASXCQf3mqLyC9GR2zgxxb6Xs1I0Hc1yuzYHv+6zrEvbS5P+zf2Fz3mj1rEaK3Yf7wmw/Rags1X42R9jPcc=
branches:
  except:
    - /^prototypes\/.*$/
