sudo: false
language: ruby
cache:
  bundler: true
  directories:
  - node_modules
  - tmp/cache/assets/test
  - vendor/assets/bower_components
env:
  global:
  - secure: ZbggxPXsIVr8W4yO7oLH0Ps+jaCcZcwvR3/wUCjwtaO/FdmHhE8LkN9If14IYyiegEmF4kmlqH03+Svb1CGOgt54kQ4wCuN8dCNH+hGS39Vn/E2ngC/h5U/wf99m4IVzBPzg0IcKN9OWCWzRRMUM+X0Zq04zuekWwUMKlERAajk=
  - secure: TalQfqJYJofCCUZdzC75EEQtNtD7DyFDFa0IGziaz0H8xxGF7sTG/Sn02ufVxXEylfdCYFQYERfjBz/aajSUZ/7mVDFvokiJaYbGCZNboKmwzfRcYxNz5k4MwrTzPdkebjyEYaYHsMrdOmNkI+4UKiwqkew4n10EC++vfDgyTYQ=
  - DATABASE_URL=postgres://postgres@localhost:5432/travis_ci_test
node_js:
- '0.10'
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
before_script:
- npm install
- "./bin/rake db:setup RAILS_ENV=test"
deploy:
  provider: heroku
  api_key:
    secure: Suvlts2UlzvnyYWJ1Y+c97nQOg3T3BCS+y8chl0xUXMJTip/jpQ7hxc7ClBi6BsKJ2WpC+CAXNK0lwoxRFhZ+ieeKO3RuUXwbo6DL/6fhHSUGZLfhjgMmH9Nk+mvNipWk6nqV3HYaveY0OCIgYXVi3kJLP7k+1M5AenmJ0rWSRA=
  app: staging-output-pensionwise
  on:
    repo: guidance-guarantee-programme/output
  run: "./bin/rake db:migrate"
notifications:
  slack:
    rooms:
      secure: imKpfnI2QtNT/ylZwv0727nlBw+AbCRfHV9u+Yr7OA/1PaqtQuKtuudo2LViMsTb1NTmolA0IEoxdmpz/Ec+l7w11y4KOI6qUv8b4z7lXYkI4ynDzB/lfJmCd8zrmTNHKsRp1XzqvrPGNDWyuupII4MaVE3nAB7zTSLRR5WWpFI=
