default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: record_of_guidance_development

test:
  <<: *default
  database: record_of_guidance_test
