class AppointmentSummaryPage < SitePrism::Page
  set_url '/appointment_summaries/new'

  element :name, '.t-name'
  element :email_address, '.t-email-address'
  element :address_line_1, '.t-address-line-1'
  element :address_line_2, '.t-address-line-2'
  element :address_line_3, '.t-address-line-3'
  element :town, '.t-town'
  element :county, '.t-county'
  element :postcode, '.t-postcode'
  element :date_of_appointment, '.t-date-of-appointment'
  element :value_of_pension_pots, '.t-value-of-pension-pots'
  element :income_in_retirement_pension, '.t-income-in-retirement-pension'
  element :income_in_retirement_other, '.t-income-in-retirement-other'
  element :guider_name, '.t-guider-name'
  element :guider_organisation_tpas, '.t-guider-organisation-tpas'
  element :guider_organisation_cab, '.t-guider-organisation-cab'
  element :continue_working, '.t-continue-working'
  element :unsure, '.t-unsure'
  element :leave_inheritance, '.t-leave-inheritance'
  element :wants_flexibility, '.t-wants-flexibility'
  element :wants_security, '.t-wants-security'
  element :wants_lump_sum, '.t-wants-lump-sum'
  element :poor_health, '.t-poor-health'
  element :submit, '.t-submit'
end
